apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  template: # Template for pods
    metadata:
      name: webapp
      labels:
        app: webapp # used for select replicated pods in a service.
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
---
apiVersion: v1
kind: Pod
metadata:
  name: fleetman-queue
  labels:
    app: fleetman-queue
    release: '1'
spec:
  containers:
    - name: message-queue
      image: richardchesterwood/k8s-fleetman-queue:release1
