apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector: # The key-value pairs of the target pod's label.
    app: webapp
  ports:
  - name: http
    port: 80
    nodePort: 30080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: fleetman-queue
    release: '1'
  ports:
    - name: http
      port: 8161
      nodePort: 30010
  type: NodePort
