apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector: # The key-value pairs of the target pod's label.
    app: webapp
    release: '0-5'
  ports:
  - name: http
    port: 80
    nodePort: 30080
  type: NodePort
